server:
  port: 8899
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
spring:
  application:
    name: market-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: MarketDb
management:
  security:
    enabled: false
logging:
  level:
    com.myapp.spring: DEBUG
    
   